general:
  use_uvloop: true

functions:
  extract_travel_requirements:
    _type: aiq.tool/extract_travel_requirements
    llm: travel_llm
    root_path: "./examples/travel_ai/data/"

  search_flights:
    _type: aiq.tool/search_flights
    root_path: "./examples/travel_ai/data/"
    api_key: "ed32a1a9f2362ccb866a496e7c807774660bd23aff2f2ed3693b6f8fd261202b"
    llm: travel_llm

llms:
  travel_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.7
    max_tokens: 4096

workflow:
  _type: react_agent
  llm_name: 23223_llm
  tool_names:
    - extract_travel_requirements
    - search_flights
  verbose: true